"""song embeddings and features

Revision ID: 6ba9e464c8aa
Revises: 2fc376f35408
Create Date: 2026-09-25 21:50:35.178337

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ba9e464c8aa"
down_revision: str | Sequence[str] | None = "2fc376f35408"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector adds the `vector` column type (not detected by autogenerate).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "song_embeddings",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
        ),
        sa.PrimaryKeyConstraint("song_id", "model_name"),
    )
    op.create_table(
        "song_features",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("feature_set", sa.String(length=160), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
        ),
        sa.PrimaryKeyConstraint("song_id", "feature_set"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("song_features")
    op.drop_table("song_embeddings")
    # ### end Alembic commands ###
