"""generation requests

Revision ID: ff8f8c992a98
Revises: ae935b9b38a6
Create Date: 2026-09-26 14:01:42.551581

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff8f8c992a98"
down_revision: str | Sequence[str] | None = "ae935b9b38a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("parsed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('generating', 'ready', 'failed')", name="valid_status"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["rating_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_generation_requests_status"), "generation_requests", ["status"], unique=False
    )
    op.add_column("generation_jobs", sa.Column("request_id", sa.Integer(), nullable=True))
    op.add_column("generation_jobs", sa.Column("variant", sa.String(length=16), nullable=True))
    op.create_index(
        op.f("ix_generation_jobs_request_id"), "generation_jobs", ["request_id"], unique=False
    )
    op.create_foreign_key(
        "generation_jobs_request_id_fkey",
        "generation_jobs",
        "generation_requests",
        ["request_id"],
        ["id"],
    )
    # ### end Alembic commands ###
    # Autogenerate doesn't detect new CHECK constraints on existing tables.
    op.create_check_constraint(
        "valid_variant", "generation_jobs", "variant IS NULL OR variant IN ('steered', 'plain')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("valid_variant", "generation_jobs", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("generation_jobs_request_id_fkey", "generation_jobs", type_="foreignkey")
    op.drop_index(op.f("ix_generation_jobs_request_id"), table_name="generation_jobs")
    op.drop_column("generation_jobs", "variant")
    op.drop_column("generation_jobs", "request_id")
    op.drop_index(op.f("ix_generation_requests_status"), table_name="generation_requests")
    op.drop_table("generation_requests")
    # ### end Alembic commands ###
