"""rating sessions and slates

Revision ID: ae935b9b38a6
Revises: 6ba9e464c8aa
Create Date: 2026-09-25 23:11:24.149889

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae935b9b38a6"
down_revision: str | Sequence[str] | None = "6ba9e464c8aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rating_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("context", sa.String(length=32), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "slates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("policy", sa.String(length=32), nullable=False),
        sa.Column("model_name", sa.String(length=32), nullable=False),
        sa.Column("n_training_choices", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("chosen_song_id", sa.Integer(), nullable=True),
        sa.Column("worst_song_id", sa.Integer(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(chosen_song_id IS NULL) = (answered_at IS NULL)", name="answer_complete"
        ),
        sa.CheckConstraint("worst_song_id IS NULL OR worst_song_id <> chosen_song_id"),
        sa.ForeignKeyConstraint(
            ["chosen_song_id"],
            ["songs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["rating_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worst_song_id"],
            ["songs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_slates_session_id"), "slates", ["session_id"], unique=False)
    op.create_table(
        "slate_items",
        sa.Column("slate_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.CheckConstraint("source IN ('model', 'random')", name="valid_source"),
        sa.ForeignKeyConstraint(
            ["slate_id"],
            ["slates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
        ),
        sa.PrimaryKeyConstraint("slate_id", "song_id"),
        sa.UniqueConstraint("slate_id", "position"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slate_items")
    op.drop_index(op.f("ix_slates_session_id"), table_name="slates")
    op.drop_table("slates")
    op.drop_table("rating_sessions")
    # ### end Alembic commands ###
