"""reference songs

Phase 6: uploaded reference songs (embedded for similarity search), and generation
jobs that imitate one (variant "reference").

Revision ID: 0df9b0461afb
Revises: 5c1d7e2a9b40
Create Date: 2026-09-28 11:17:28.181591

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0df9b0461afb"
down_revision: str | Sequence[str] | None = "5c1d7e2a9b40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reference_songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("audio_path", sa.Text(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'ready') = (embedding IS NOT NULL)", name="ready_means_embedded"
        ),
        sa.CheckConstraint("status IN ('pending', 'ready', 'failed')", name="valid_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reference_songs_status"), "reference_songs", ["status"], unique=False)
    op.add_column("generation_jobs", sa.Column("reference_id", sa.Integer(), nullable=True))
    op.drop_constraint(
        "generation_jobs_prompt_id_seed_duration_s_bpm_model_name_key",
        "generation_jobs",
        type_="unique",
    )
    op.create_unique_constraint(
        "generation_jobs_same_settings_key",
        "generation_jobs",
        ["prompt_id", "seed", "duration_s", "bpm", "model_name", "reference_id"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_foreign_key(
        "generation_jobs_reference_id_fkey",
        "generation_jobs",
        "reference_songs",
        ["reference_id"],
        ["id"],
    )
    # ### end Alembic commands ###
    # Autogenerate doesn't detect changed CHECK constraints.
    op.drop_constraint("valid_variant", "generation_jobs", type_="check")
    op.create_check_constraint(
        "valid_variant",
        "generation_jobs",
        "variant IS NULL OR variant IN ('steered', 'plain', 'reference')",
    )


def downgrade() -> None:
    """Downgrade schema. Lossy: reference jobs lose their variant and reference."""
    op.execute("UPDATE generation_jobs SET variant = NULL WHERE variant = 'reference'")
    op.drop_constraint("valid_variant", "generation_jobs", type_="check")
    op.create_check_constraint(
        "valid_variant", "generation_jobs", "variant IS NULL OR variant IN ('steered', 'plain')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("generation_jobs_reference_id_fkey", "generation_jobs", type_="foreignkey")
    op.drop_constraint("generation_jobs_same_settings_key", "generation_jobs", type_="unique")
    op.create_unique_constraint(
        "generation_jobs_prompt_id_seed_duration_s_bpm_model_name_key",
        "generation_jobs",
        ["prompt_id", "seed", "duration_s", "bpm", "model_name"],
        postgresql_nulls_not_distinct=True,
    )
    op.drop_column("generation_jobs", "reference_id")
    op.drop_index(op.f("ix_reference_songs_status"), table_name="reference_songs")
    op.drop_table("reference_songs")
    # ### end Alembic commands ###
