"""HTTP API for the rating app.

Run:  uv run uvicorn --factory music_gen.api.app:build_app --port 8000
Docs: http://localhost:8000/docs (interactive, generated by FastAPI)
"""

import logging
import os
from collections.abc import Iterator
from pathlib import Path
from typing import Annotated

from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.responses import FileResponse
from pydantic import BaseModel
from sqlalchemy import func, select
from sqlalchemy.orm import Session, sessionmaker

from music_gen import audio
from music_gen.api.requests import RequestService
from music_gen.api.service import InvalidAnswer, Recommender, SlateAlreadyAnswered, SlateNotFound
from music_gen.db import GenerationJob, Prompt, RatingSession, ReferenceSong, Slate, Song
from music_gen.references import InvalidReference, save_reference, similar_songs

logger = logging.getLogger(__name__)

# Playback loudness. Measured on the 540-song pool: at -20 dBFS only 81% of songs can
# be raised to the target without clipping (10 dB spread remains); at -26 dBFS, 99.4%
# land within 1 dB of each other. Quieter overall, but fair: turn the volume up.
PLAYBACK_DBFS = -26.0


class StartSession(BaseModel):
    context: str


class SessionOut(BaseModel):
    session_id: int
    context: str


class SongOut(BaseModel):
    song_id: int
    audio_url: str


class SlateOut(BaseModel):
    slate_id: int
    songs: list[SongOut]  # in display order. Deliberately no "source" or "score": rating is blind.


class Answer(BaseModel):
    chosen_song_id: int
    worst_song_id: int | None = None


class AnswerOut(BaseModel):
    n_ratings: int


class CreateRequest(BaseModel):
    text: str
    context: str
    reference_id: int | None = None  # imitate this uploaded song (Phase 6)


class RequestOut(BaseModel):
    request_id: int
    tags: list[str]  # what the parser understood, shown back to the listener
    energy: str | None


class RequestStatusOut(BaseModel):
    status: str  # generating | ready | failed
    n_done: int
    n_failed: int
    n_total: int
    slate: SlateOut | None  # once ready. Steered/plain labels are never sent: blind.
    error: str | None


class SimilarSongOut(BaseModel):
    song_id: int
    audio_url: str
    prompt: str
    distance: float  # cosine distance: 0 = same direction


class ReferenceOut(BaseModel):
    reference_id: int
    filename: str
    duration_s: float
    status: str  # pending (worker hasn't embedded it yet) | ready | failed
    error: str | None
    audio_url: str
    similar: list[SimilarSongOut]  # closest library songs, once ready


def reference_out(session: Session, reference: ReferenceSong) -> ReferenceOut:
    nearest = similar_songs(session, reference)
    prompts = dict(
        session.execute(
            select(Song.id, Prompt.text)
            .join(GenerationJob, Song.job_id == GenerationJob.id)
            .join(Prompt, GenerationJob.prompt_id == Prompt.id)
            .where(Song.id.in_([song_id for song_id, _ in nearest]))
        ).all()
    )
    return ReferenceOut(
        reference_id=reference.id,
        filename=reference.filename,
        duration_s=reference.duration_s,
        status=reference.status,
        error=reference.error,
        audio_url=f"/api/references/{reference.id}/audio",
        similar=[
            SimilarSongOut(
                song_id=song_id,
                audio_url=f"/api/songs/{song_id}/audio",
                prompt=prompts[song_id],
                distance=distance,
            )
            for song_id, distance in nearest
        ],
    )


def slate_out(slate: Slate) -> SlateOut:
    return SlateOut(
        slate_id=slate.id,
        songs=[
            SongOut(song_id=item.song_id, audio_url=f"/api/songs/{item.song_id}/audio")
            for item in slate.items
        ],
    )


def create_app(
    session_factory: sessionmaker,
    recommender: Recommender,
    data_dir: Path,
    requests: RequestService | None = None,
) -> FastAPI:
    app = FastAPI(title="Adaptive music rating API")

    def db() -> Iterator[Session]:
        with session_factory() as session:
            yield session

    Db = Annotated[Session, Depends(db)]  # one database session per request

    @app.get("/api/contexts")
    def contexts() -> dict[str, str]:
        return recommender.contexts

    @app.post("/api/sessions", response_model=SessionOut)
    def start_session(body: StartSession, session: Db) -> SessionOut:
        try:
            rs = recommender.start_session(session, body.context)
        except InvalidAnswer as e:
            raise HTTPException(422, str(e)) from e
        return SessionOut(session_id=rs.id, context=rs.context)

    @app.post("/api/sessions/{session_id}/slates", response_model=SlateOut)
    def next_slate(session_id: int, session: Db) -> SlateOut:
        try:
            slate = recommender.next_slate(session, session_id)
        except SlateNotFound as e:
            raise HTTPException(404, str(e)) from e
        return slate_out(slate)

    @app.post("/api/slates/{slate_id}/answer", response_model=AnswerOut)
    def answer(slate_id: int, body: Answer, session: Db) -> AnswerOut:
        try:
            recommender.record_answer(session, slate_id, body.chosen_song_id, body.worst_song_id)
        except SlateNotFound as e:
            raise HTTPException(404, str(e)) from e
        except SlateAlreadyAnswered as e:
            raise HTTPException(409, str(e)) from e
        except InvalidAnswer as e:
            raise HTTPException(422, str(e)) from e
        n = session.scalar(select(func.count()).where(Slate.answered_at.is_not(None)))
        return AnswerOut(n_ratings=n)

    @app.get("/api/songs/{song_id}/audio")
    def song_audio(song_id: int, session: Db) -> FileResponse:
        song = session.get(Song, song_id)
        if song is None:
            raise HTTPException(404, f"song {song_id} doesn't exist")
        # Normalize once and cache the file: serving a real file lets FileResponse
        # answer HTTP range requests, which browsers need to let you seek in a song.
        path = data_dir / "audio" / "playback" / f"{PLAYBACK_DBFS:+.0f}dB" / f"song_{song_id}.wav"
        if not path.exists():
            clip, sr = audio.load_audio(data_dir / song.audio_path)
            partial = path.with_suffix(".partial.wav")
            audio.save_wav(audio.normalize_loudness(clip, target_dbfs=PLAYBACK_DBFS), sr, partial)
            os.replace(partial, path)  # atomic: never serve a half-written file
        return FileResponse(path, media_type="audio/wav")

    @app.post("/api/requests", response_model=RequestOut)
    def create_request(body: CreateRequest, session: Db) -> RequestOut:
        if requests is None:
            raise HTTPException(503, "live generation isn't enabled on this server")
        try:
            request = requests.create(session, body.text, body.context, body.reference_id)
        except InvalidAnswer as e:
            raise HTTPException(422, str(e)) from e
        return RequestOut(
            request_id=request.id, tags=request.parsed["tags"], energy=request.parsed["energy"]
        )

    @app.get("/api/requests/{request_id}", response_model=RequestStatusOut)
    def request_status(request_id: int, session: Db) -> RequestStatusOut:
        if requests is None:
            raise HTTPException(503, "live generation isn't enabled on this server")
        try:
            status = requests.status(session, request_id)
        except SlateNotFound as e:
            raise HTTPException(404, str(e)) from e
        return RequestStatusOut(
            status=status.status,
            n_done=status.n_done,
            n_failed=status.n_failed,
            n_total=status.n_total,
            slate=slate_out(status.slate) if status.slate else None,
            error=status.error,
        )

    @app.post("/api/references", response_model=ReferenceOut)
    async def upload_reference(filename: str, request: Request, session: Db) -> ReferenceOut:
        """The request body is the raw audio file (no multipart form needed)."""
        try:
            reference = save_reference(session, data_dir, filename, await request.body())
        except InvalidReference as e:
            raise HTTPException(422, str(e)) from e
        return reference_out(session, reference)

    @app.get("/api/references/{reference_id}", response_model=ReferenceOut)
    def reference(reference_id: int, session: Db) -> ReferenceOut:
        reference = session.get(ReferenceSong, reference_id)
        if reference is None:
            raise HTTPException(404, f"reference song {reference_id} doesn't exist")
        return reference_out(session, reference)

    @app.get("/api/references/{reference_id}/audio")
    def reference_audio(reference_id: int, session: Db) -> FileResponse:
        reference = session.get(ReferenceSong, reference_id)
        if reference is None:
            raise HTTPException(404, f"reference song {reference_id} doesn't exist")
        return FileResponse(data_dir / reference.audio_path)

    @app.get("/api/profile")
    def profile(session: Db) -> dict:
        return recommender.profile(session)

    @app.get("/api/stats")
    def stats(session: Db) -> dict:
        rows = session.execute(
            select(RatingSession.context, func.count(Slate.id))
            .join(Slate, Slate.session_id == RatingSession.id)
            .where(Slate.answered_at.is_not(None))
            .group_by(RatingSession.context)
        ).all()
        per_context = {c: 0 for c in recommender.contexts} | dict(rows)
        return {"n_ratings": sum(per_context.values()), "by_context": per_context}

    return app


def build_app() -> FastAPI:
    """Wire the app to the real database and feature space (used by uvicorn)."""
    from music_gen.config import get_settings
    from music_gen.db import make_session_factory
    from music_gen.features.space import FeatureSpace
    from music_gen.features.tags import load_tags
    from music_gen.generation.acestep import MODEL_NAME
    from music_gen.logging_setup import configure_logging
    from music_gen.personalization.data import DbSongSource, load_contexts
    from music_gen.personalization.steering import load_request_words

    settings = get_settings()
    configure_logging(settings.log_level)
    session_factory = make_session_factory(settings.database_url)
    space = FeatureSpace.load(settings.data_dir / "models" / "feature_space_v1.npz")
    vocab = load_tags(Path("configs/tags.yaml"))
    source = DbSongSource(space, vocab)
    with session_factory() as session:
        songs = source.load(session)
    logger.info("Loaded %d songs x %d features", *songs.x.shape)
    recommender = Recommender(songs, load_contexts(Path("configs/contexts.yaml")), source=source)
    requests = RequestService(
        recommender,
        vocab,
        load_request_words(Path("configs/request_words.yaml"), vocab),
        MODEL_NAME,
    )
    return create_app(session_factory, recommender, settings.data_dir, requests)
